import { createContext, useContext, useEffect, useMemo, useState } from 'react';
import type { ReactNode } from 'react';

export type AppLanguage = 'ko' | 'en' | 'vi' | 'my' | 'km';

type LanguageOption = {
  code: AppLanguage;
  label: string;
};

type LanguageContextValue = {
  currentLanguage: AppLanguage;
  currentLanguageLabel: string;
  languages: LanguageOption[];
  setLanguage: (language: AppLanguage) => void;
};

const languages: LanguageOption[] = [
  { code: 'ko', label: '한국어' },
  { code: 'en', label: 'English' },
  { code: 'vi', label: 'Tiếng Việt' },
  { code: 'my', label: 'မြန်မာဘာသာ' },
  { code: 'km', label: 'ភាសាខ្មែរ' },
];

const vietnameseDictionary: Record<string, string> = {
  '준또배기 Compliance AI 플랫폼에 오신 것을 환영합니다.': 'Chào mừng bạn đến với nền tảng AI tuân thủ JunttoBaegi.',
  '준또배기': 'JunttoBaegi',
  'JB금융그룹': 'Tập đoàn Tài chính JB',
  'Compliance AI': 'AI tuân thủ',
  '법무팀': 'Đội pháp vụ',
  'Compliance 전문 AI': 'AI chuyên về tuân thủ',
  '플랫폼': 'Nền tảng',

  '한국어': 'Tiếng Hàn',
  '영어': 'Tiếng Anh',
  '베트남어': 'Tiếng Việt',
  '미얀마어': 'Tiếng Myanmar',
  '캄보디아어': 'Tiếng Khmer',
  '언어 및 지역': 'Ngôn ngữ và khu vực',
  '언어': 'Ngôn ngữ',
  '시간대': 'Múi giờ',
  '날짜 형식': 'Định dạng ngày',

  '홈': 'Trang chủ',
  'AI 채팅': 'Trò chuyện AI',
  'AI 검토': 'Đánh giá AI',
  '교육 자료 제작': 'Tạo tài liệu đào tạo',
  '라이브러리': 'Thư viện',
  '캘린더': 'Lịch',
  '설정': 'Cài đặt',
  '알림': 'Thông báo',
  '알림 설정': 'Cài đặt thông báo',
  '프로필': 'Hồ sơ',
  '계정 설정': 'Cài đặt tài khoản',
  '화면 설정': 'Cài đặt giao diện',
  '개인정보': 'Thông tin cá nhân',
  '데이터 관리': 'Quản lý dữ liệu',
  '도움말': 'Trợ giúp',
  '로그아웃': 'Đăng xuất',
  '모두 보기': 'Xem tất cả',
  '전체 보기': 'Xem tất cả',
  '전체': 'Tất cả',
  '저장': 'Lưu',
  '취소': 'Hủy',
  '변경': 'Thay đổi',
  '다운로드': 'Tải xuống',
  '검색': 'Tìm kiếm',
  '추가': 'Thêm',
  '초기화': 'Đặt lại',
  '위젯 추가': 'Thêm tiện ích',
  '새로고침': 'Làm mới',
  '전체화면': 'Toàn màn hình',
  '위젯 제거': 'Xóa tiện ích',
  '정보': 'Thông tin',

  '위젯을 드래그해서 홈 레이아웃을 자유롭게 구성하세요.': 'Kéo thả tiện ích để tùy chỉnh bố cục trang chủ.',
  '홈에 추가할 위젯을 선택하세요.': 'Chọn tiện ích để thêm vào trang chủ.',
  '그리드 크기 미리보기': 'Xem trước kích thước lưới',
  '추가한 위젯은 드래그해서 순서를 바꾸거나 크기를 조절할 수 있습니다.': 'Bạn có thể kéo tiện ích đã thêm để đổi thứ tự hoặc điều chỉnh kích thước.',
  '위젯을 추가하여 홈을 구성하세요.': 'Thêm tiện ích để tạo trang chủ.',
  '드래그해서 이동': 'Kéo để di chuyển',
  '대형 (2x4)': 'Lớn (2x4)',
  '세로형 (1x4)': 'Dọc (1x4)',
  '규정 및 법령에 대한 실시간 AI 질의응답': 'Hỏi đáp AI theo thời gian thực về quy định và pháp luật',
  '문서의 규정 준수 여부를 AI가 자동 검토': 'AI tự động đánh giá mức độ tuân thủ của tài liệu',
  '법안 변경사항 기반 교육 초안 생성': 'Tạo bản nháp đào tạo dựa trên thay đổi pháp luật',
  '검토 결과, 원본 문서, 보고서 보관함': 'Kho lưu kết quả đánh giá, tài liệu gốc và báo cáo',
  'Compliance 관련 일정 및 마감일': 'Lịch và thời hạn liên quan đến tuân thủ',
  '월간 일정 현황을 달력 형태로 확인': 'Xem tình trạng lịch tháng dưới dạng lịch',
  '중요 업데이트 및 알림': 'Cập nhật và thông báo quan trọng',

  '안녕하세요! JB금융그룹 Compliance AI assistant입니다. 무엇을 도와드릴까요?': 'Xin chào! Tôi là assistant AI tuân thủ của Tập đoàn Tài chính JB. Tôi có thể giúp gì cho bạn?',
  '안녕하세요! JB금융그룹 Compliance AI assistant입니다.': 'Xin chào! Tôi là assistant AI tuân thủ của Tập đoàn Tài chính JB.',
  '안녕하세요. JB금융그룹 Compliance AI assistant입니다. 규정, 법령, 내부 정책에 대해 무엇이든 물어보세요.': 'Xin chào. Tôi là assistant AI tuân thủ của Tập đoàn Tài chính JB. Hãy hỏi tôi về quy định, pháp luật hoặc chính sách nội bộ.',
  '추천 질문': 'Câu hỏi gợi ý',
  '추천 질문:': 'Câu hỏi gợi ý:',
  '최근 금융규제 변경사항은?': 'Những thay đổi gần đây về quy định tài chính là gì?',
  '내부통제 가이드라인 확인': 'Kiểm tra hướng dẫn kiểm soát nội bộ',
  '리스크 평가 도구 사용법': 'Cách sử dụng công cụ đánh giá rủi ro',
  '최근 금융소비자보호법 개정 내용은?': 'Nội dung sửa đổi gần đây của Luật bảo vệ người tiêu dùng tài chính là gì?',
  '신규 대출 상품 출시 전 Compliance 체크리스트': 'Danh sách kiểm tra tuân thủ trước khi ra mắt sản phẩm vay mới',
  'AML 정기 평가 필수 항목': 'Các hạng mục bắt buộc trong đánh giá AML định kỳ',
  '내부통제 시스템 운영 가이드라인': 'Hướng dẫn vận hành hệ thống kiểm soát nội bộ',
  '질문을 입력하세요...': 'Nhập câu hỏi...',
  'Compliance 관련 질문을 입력하세요...': 'Nhập câu hỏi liên quan đến tuân thủ...',
  'AI assistant': 'AI assistant',
  '규정 기반 AI Compliance assistant': 'assistant AI tuân thủ dựa trên quy định',
  '새 대화': 'Cuộc trò chuyện mới',
  '새 채팅': 'Cuộc trò chuyện mới',
  '채팅 목록': 'Danh sách trò chuyện',
  '과거 채팅 검색': 'Tìm kiếm trò chuyện cũ',
  '고정됨': 'Đã ghim',
  '최근 채팅': 'Trò chuyện gần đây',
  '핀 고정': 'Ghim',
  '핀 고정 해제': 'Bỏ ghim',
  '검색된 고정 채팅이 없습니다.': 'Không có trò chuyện đã ghim phù hợp.',
  '핀 고정한 채팅이 없습니다.': 'Chưa có trò chuyện được ghim.',
  '검색된 채팅이 없습니다.': 'Không có trò chuyện phù hợp.',
  '아직 과거 채팅이 없습니다.': 'Chưa có lịch sử trò chuyện.',
  '관련 규정과 내부 문서를 검색하고 있습니다.': 'Đang tìm kiếm quy định và tài liệu nội bộ liên quan.',
  '검토 결과 예시는 다음과 같습니다.': 'Ví dụ kết quả rà soát như sau.',
  '자세한 내용은 관련 규정 문서를 확인해 주세요.': 'Vui lòng kiểm tra tài liệu quy định liên quan để biết thêm chi tiết.',

  '문서 AI 검토': 'Đánh giá tài liệu bằng AI',
  '홈에서 업로드하고 바로 검토 요청': 'Tải lên từ trang chủ và yêu cầu đánh giá ngay',
  '검토 요청': 'Yêu cầu đánh giá',
  '검토 요청이 완료되었습니다.': 'Yêu cầu đánh giá đã hoàn tất.',
  'AI 검토가 필요한 문장이 감지되었습니다.': 'Đã phát hiện câu cần AI đánh giá.',
  '규정 문구와 고지 내용을 한 번 더 확인하세요.': 'Vui lòng kiểm tra lại nội dung quy định và thông báo.',
  '규정 준수 검토를 위한 문서 업로드': 'Tải tài liệu lên để kiểm tra tuân thủ',
  '검토할 문서를 끌어다 놓거나 파일을 선택해 업로드하세요.': 'Kéo thả tài liệu cần kiểm tra hoặc chọn tệp để tải lên.',
  '지원 형식: PDF, DOCX, TXT': 'Định dạng hỗ trợ: PDF, DOCX, TXT',
  '파일 선택': 'Chọn tệp',
  'PDF, DOCX, TXT 파일만 업로드할 수 있습니다.': 'Chỉ có thể tải lên tệp PDF, DOCX, TXT.',
  '최근 검토': 'Đánh giá gần đây',
  '카드를 클릭하면 작업 상세를 확인할 수 있습니다.': 'Nhấp vào thẻ để xem chi tiết công việc.',
  '제목, 요청자, 파일명 검색': 'Tìm theo tiêu đề, người yêu cầu, tên tệp',
  '검색 결과가 없습니다.': 'Không có kết quả tìm kiếm.',
  '요청자': 'Người yêu cầu',
  '일시': 'Thời gian',
  '이슈': 'Vấn đề',
  '원본 다운로드': 'Tải bản gốc',
  '수정본 다운로드': 'Tải bản đã sửa',
  'AI 검토 결과': 'Kết quả đánh giá AI',
  '위험문장 하이라이트': 'Câu rủi ro được tô sáng',
  '수정 제안': 'Đề xuất chỉnh sửa',
  '원본 문서': 'Tài liệu gốc',
  '수정본': 'Bản đã sửa',
  '닫기': 'Đóng',
  '완료': 'Hoàn tất',
  '검토 중': 'Đang đánh giá',
  '확인 필요': 'Cần xác nhận',
  '검토 완료': 'Đánh giá hoàn tất',
  '대기중': 'Đang chờ',

  '새 법안을 업로드하고, 준법자문가가 교육하면 좋겠다고 판단한 내용을 포스터와 요청 자료로 정리합니다.': 'Tải lên luật mới và sắp xếp những nội dung chuyên gia tuân thủ cho rằng nên đào tạo thành poster và tài liệu yêu cầu.',
  '준법자문가 시나리오': 'Kịch bản chuyên gia tuân thủ',
  '새로운 법안 또는 개정안 업로드': 'Tải lên luật mới hoặc bản sửa đổi',
  '현재 분석 문서': 'Tài liệu đang phân tích',
  'PDF, DOCX, TXT 형식의 법안/개정안 요약 문서를 넣어주세요.': 'Vui lòng thêm tài liệu tóm tắt luật hoặc bản sửa đổi ở định dạng PDF, DOCX, TXT.',
  '준법자문가 검토 포인트': 'Điểm rà soát của chuyên gia tuân thủ',
  '기존': 'Trước đây',
  '권장 교육 대상': 'Đối tượng đào tạo đề xuất',
  '선택': 'Chọn',
  '포스터 반영': 'Đưa vào poster',
  '제작하기': 'Tạo mới',
  '홈에서 업로드하고 바로 제작 요청': 'Tải lên từ trang chủ và yêu cầu tạo ngay',
  '제작 요청': 'Yêu cầu tạo',
  '교육 자료 제작 열기': 'Mở tạo tài liệu đào tạo',
  '전체 검토 보기': 'Xem toàn bộ đánh giá',
  '전체 채팅 열기': 'Mở toàn bộ trò chuyện',
  '포스터 갤러리': 'Thư viện poster',
  '포스터 문구 다운로드': 'Tải nội dung poster',
  '요청하기': 'Gửi yêu cầu',
  '요청 내용': 'Nội dung yêu cầu',
  'PPT 개요': 'Dàn ý PPT',
  '교육 문구': 'Nội dung đào tạo',
  '교육 담당자 제공용 PPT 개요': 'Dàn ý PPT cung cấp cho người phụ trách đào tạo',
  '교육 안내 문구': 'Nội dung thông báo đào tạo',
  '결과 다운로드': 'Tải kết quả',
  '선택된 교육 포인트를 기반으로 만들어진 포스터를 갤러리 형태로 확인합니다.': 'Xem các poster được tạo dựa trên những điểm đào tạo đã chọn dưới dạng thư viện.',
  '개 포스터': 'poster',
  '개정 법안 핵심 교육 포스터': 'Poster đào tạo trọng tâm về luật sửa đổi',
  '필수 안내': 'Thông báo bắt buộc',
  '현장 체크': 'Kiểm tra tại hiện trường',
  '고객 안내 문구와 내부 절차를 함께 점검': 'Kiểm tra đồng thời nội dung thông báo khách hàng và quy trình nội bộ',
  '대상 즉시 공유': 'chia sẻ ngay cho đối tượng',
  '교육 목적': 'Mục tiêu đào tạo',
  '핵심 변경사항': 'Thay đổi trọng tâm',
  '현장 적용 체크포인트': 'Điểm kiểm tra áp dụng tại hiện trường',
  '교육 진행 제안': 'Đề xuất triển khai đào tạo',
  '포스터로 핵심 문구 우선 공지': 'Thông báo trước các nội dung chính bằng poster',
  '담당 부서별 질의 취합': 'Tổng hợp câu hỏi theo bộ phận phụ trách',
  '교육 이수 여부와 관련 문서 최신화 확인': 'Xác nhận hoàn thành đào tạo và cập nhật tài liệu liên quan',
  '주요 안내 문구': 'Nội dung thông báo chính',
  '교육 대상': 'Đối tượng đào tạo',

  '다가오는 일정': 'Lịch sắp tới',
  '건 예정': 'mục sắp tới',
  '건 일정': 'mục lịch',
  '예정': 'sắp tới',
  '예정된 일정 없음': 'Không có lịch sắp tới',
  '예정된 일정이 없습니다.': 'Không có lịch sắp tới.',
  'Compliance 일정 및 이벤트 관리': 'Quản lý lịch và sự kiện tuân thủ',
  '일정 추가': 'Thêm lịch',
  '오늘': 'Hôm nay',
  '오늘의 일정': 'Lịch hôm nay',
  '일정이 없습니다.': 'Không có lịch.',
  '새 일정 추가': 'Thêm lịch mới',
  '제목': 'Tiêu đề',
  '카테고리': 'Danh mục',
  '기간': 'Thời gian',
  '시작 시간': 'Giờ bắt đầu',
  '종료 시간': 'Giờ kết thúc',
  '장소': 'Địa điểm',
  '관할 부서': 'Bộ phận phụ trách',
  '메모': 'Ghi chú',
  '일정 제목을 입력하세요': 'Nhập tiêu đề lịch',
  '장소를 입력하세요': 'Nhập địa điểm',
  '추가 메모를 입력하세요': 'Nhập ghi chú bổ sung',
  '시간 미정': 'Chưa xác định thời gian',
  '장소 미정': 'Chưa xác định địa điểm',
  '미지정': 'Chưa chỉ định',
  '세미나': 'Hội thảo',
  '감사': 'Kiểm toán',
  '워크샵': 'Workshop',
  '교육': 'Đào tạo',
  '회의': 'Họp',
  '점검': 'Kiểm tra',
  '기타': 'Khác',

  '검토 결과, 원본 문서, 보고서를 한곳에서 확인하세요.': 'Xem kết quả đánh giá, tài liệu gốc và báo cáo ở một nơi.',
  '목록 보기': 'Xem dạng danh sách',
  '그리드 보기': 'Xem dạng lưới',
  '파일명, 확장자, 유형 검색': 'Tìm theo tên tệp, phần mở rộng, loại',
  '이미지': 'Hình ảnh',
  '파일': 'Tệp',
  '검토 결과': 'Kết quả đánh giá',
  '원본': 'Bản gốc',
  '보고서': 'Báo cáo',
  '유형': 'Loại',
  '최근 수정': 'Cập nhật gần đây',

  '전체 알림 내역': 'Toàn bộ lịch sử thông báo',
  '모두 읽음 처리': 'Đánh dấu tất cả là đã đọc',
  '안읽음': 'Chưa đọc',
  '모두 읽음': 'Tất cả đã đọc',
  '방금': 'Vừa xong',
  '분 전': 'phút trước',
  '5분 전': '5 phút trước',
  '읽지 않음': 'Chưa đọc',
  '읽음': 'Đã đọc',
  '읽지 않은 알림이 없습니다.': 'Không có thông báo chưa đọc.',
  '알림이 없습니다.': 'Không có thông báo.',
  '최근 알림': 'Thông báo gần đây',
  '새 알림': 'Thông báo mới',
  '새 알림 없음': 'Không có thông báo mới',
  '모든 알림 보기': 'Xem tất cả thông báo',
  '교육 포스터 생성 완료': 'Tạo poster đào tạo hoàn tất',
  '광고시안_Ver2_검토보고서.txt가 라이브러리에 저장되었습니다.': '광고시안_Ver2_검토보고서.txt đã được lưu vào thư viện.',
  '금융소비자보호법_교육포스터.png가 라이브러리에 저장되었습니다.': '금융소비자보호법_교육포스터.png đã được lưu vào thư viện.',
  '금융소비자보호법_교육자료.pptx가 라이브러리에 저장되었습니다.': '금융소비자보호법_교육자료.pptx đã được lưu vào thư viện.',

  '계정과 시스템 설정을 관리하세요.': 'Quản lý tài khoản và cài đặt hệ thống.',
  '준비 중인 설정 영역입니다.': 'Khu vực cài đặt đang được chuẩn bị.',
  '사진 변경': 'Thay ảnh',
  '이름': 'Tên',
  '이메일': 'Email',
  '부서': 'Bộ phận',
  '직책': 'Chức danh',
  '선임 Compliance 매니저': 'Quản lý tuân thủ cấp cao',
  '이메일 알림': 'Thông báo email',
  '중요한 업데이트를 이메일로 받습니다.': 'Nhận các cập nhật quan trọng qua email.',
  '브라우저 알림': 'Thông báo trình duyệt',
  '데스크톱 알림을 받습니다.': 'Nhận thông báo trên máy tính.',
  '일정 알림': 'Thông báo lịch',
  '예정된 일정 전에 알림을 받습니다.': 'Nhận thông báo trước lịch đã lên.',
  'AI 검토 완료 알림': 'Thông báo hoàn tất đánh giá AI',
  '문서 검토가 완료되면 알림을 받습니다.': 'Nhận thông báo khi đánh giá tài liệu hoàn tất.',
  '비밀번호 변경': 'Thay đổi mật khẩu',
  '정기적인 비밀번호 변경을 권장합니다.': 'Khuyến nghị thay đổi mật khẩu định kỳ.',
  '2단계 인증': 'Xác thực hai bước',
  '계정 보안을 강화합니다.': 'Tăng cường bảo mật tài khoản.',
  '활성 세션': 'Phiên hoạt động',
  '현재 로그인된 기기 목록': 'Danh sách thiết bị đang đăng nhập',
  '현재 세션': 'Phiên hiện tại',
  '활성': 'Hoạt động',
  '테마': 'Giao diện',
  '라이트': 'Sáng',
  '다크': 'Tối',
  '시스템': 'Hệ thống',
  '컴팩트 모드': 'Chế độ thu gọn',
  'UI 요소 간격을 줄입니다.': 'Giảm khoảng cách giữa các thành phần giao diện.',

  '페이지를 찾을 수 없습니다': 'Không tìm thấy trang',
  '요청하신 주소가 존재하지 않습니다.': 'Địa chỉ bạn yêu cầu không tồn tại.',
  '홈으로 돌아가기': 'Quay về trang chủ',

  '신규 대출 상품 검토': 'Đánh giá sản phẩm vay mới',
  '신규 대출상품 설명서 검토': 'Đánh giá bản mô tả sản phẩm vay mới',
  '신규 대출상품 설명서': 'Bản mô tả sản phẩm vay mới',
  '신규_대출상품_설명서': 'ban_mo_ta_san_pham_vay_moi',
  'AML 정책 업데이트 검토': 'Đánh giá cập nhật chính sách AML',
  'AML 정책 업데이트': 'Cập nhật chính sách AML',
  'AML_정책_업데이트': 'cap_nhat_chinh_sach_AML',
  '내부통제 점검표 검토': 'Đánh giá bảng kiểm tra kiểm soát nội bộ',
  '내부통제 점검표': 'Bảng kiểm tra kiểm soát nội bộ',
  '내부통제_점검표': 'bang_kiem_tra_kiem_soat_noi_bo',
  '리스크 평가 보고서': 'Báo cáo đánh giá rủi ro',
  '금융소비자보호법_광고심의_결과': 'ket_qua_tham_dinh_quang_cao_luat_bao_ve_nguoi_tieu_dung_tai_chinh',
  'AML_이상징후_분석_보고서': 'bao_cao_phan_tich_dau_hieu_bat_thuong_AML',
  '투자설명서_원본': 'ban_goc_ban_cao_bach_dau_tu',
  '사내교육_현장사진': 'anh_hien_truong_dao_tao_noi_bo',
  '리스크_분석_차트': 'bieu_do_phan_tich_rui_ro',
  '사내': 'nội bộ',
  '투자설명서': 'bản cáo bạch đầu tư',
  '내부통제': 'kiểm soát nội bộ',
  '점검표': 'bảng kiểm tra',
  '현장사진': 'ảnh hiện trường',
  '리스크': 'rủi ro',
  '분석': 'phân tích',
  '차트': 'biểu đồ',
  '금융소비자보호법': 'Luật bảo vệ người tiêu dùng tài chính',
  '광고심의': 'thẩm định quảng cáo',
  '결과': 'kết quả',
  '이상징후': 'dấu hiệu bất thường',
  '어제': 'Hôm qua',
  '오전': 'SA',
  '오후': 'CH',
  '건': 'mục',
  '월': 'tháng',
  '년': 'năm',
  '일': 'ngày',
  '김준또': 'Kim Juntto',
  '김준법': 'Kim Junbeop',
  '박정민': 'Park Jeongmin',
  '이서연': 'Lee Seoyeon',
  '금융소비자보호법 세미나': 'Hội thảo Luật bảo vệ người tiêu dùng tài chính',
  '리스크 평가 회의': 'Họp đánh giá rủi ro',
  'AML 정기 점검': 'Kiểm tra AML định kỳ',
  'KYC 절차 교육': 'Đào tạo quy trình KYC',
  '내부통제 워크샵': 'Workshop kiểm soát nội bộ',
  '본사 대회의실': 'Phòng họp lớn trụ sở chính',
  '회의실 A': 'Phòng họp A',
  'AML팀': 'Đội AML',
  '리스크관리팀': 'Đội quản lý rủi ro',
  '준법감시팀': 'Đội giám sát tuân thủ',
  '서울': 'Seoul',
  '도쿄': 'Tokyo',
  '하노이': 'Hà Nội',
  '프놈펜': 'Phnom Penh',
  '양곤': 'Yangon',
};

const englishDictionary: Record<string, string> = {
  '준또배기 Compliance AI 플랫폼에 오신 것을 환영합니다.': 'Welcome to the JunttoBaegi Compliance AI platform.',
  '준또배기': 'JunttoBaegi',
  'JB금융그룹': 'JB Financial Group',
  'Compliance AI': 'Compliance AI',
  '법무팀': 'Legal Team',
  'Compliance 전문 AI': 'Compliance AI specialist',
  '규정 기반 AI Compliance assistant': 'Rule-based Compliance AI assistant',
  '플랫폼': 'Platform',
  '한국어': 'Korean',
  '영어': 'English',
  '베트남어': 'Vietnamese',
  '미얀마어': 'Burmese',
  '캄보디아어': 'Khmer',
  '언어 및 지역': 'Language and Region',
  '언어': 'Language',
  '시간대': 'Time Zone',
  '날짜 형식': 'Date Format',
  '홈': 'Home',
  'AI 채팅': 'AI Chat',
  'AI 검토': 'AI Review',
  '교육 자료 제작': 'Training Materials',
  '라이브러리': 'Library',
  '캘린더': 'Calendar',
  '설정': 'Settings',
  '알림': 'Notifications',
  '프로필': 'Profile',
  '로그아웃': 'Log out',
  '모두 보기': 'View all',
  '전체 보기': 'View all',
  '전체': 'All',
  '저장': 'Save',
  '취소': 'Cancel',
  '다운로드': 'Download',
  '검색': 'Search',
  '추가': 'Add',
  '삭제': 'Delete',
  '수정': 'Edit',
  '위젯 추가': 'Add widget',
  '새로고침': 'Refresh',
  '전체화면': 'Fullscreen',
  '위젯 제거': 'Remove widget',
  '위젯을 드래그해서 홈 레이아웃을 자유롭게 구성하세요.': 'Drag widgets to customize your home layout.',
  '홈에 추가할 위젯을 선택하세요.': 'Select widgets to add to Home.',
  '위젯을 추가하여 홈을 구성하세요.': 'Add widgets to build your Home.',
  '드래그해서 이동': 'Drag to move',
  '대형 (2x4)': 'Large (2x4)',
  '세로형 (1x4)': 'Vertical (1x4)',
  '규정 및 법령에 대한 실시간 AI 질의응답': 'Real-time AI Q&A for regulations and laws',
  '문서의 규정 준수 여부를 AI가 자동 검토': 'AI automatically reviews document compliance',
  '법안 변경사항 기반 교육 초안 생성': 'Create training drafts from legal changes',
  '검토 결과, 원본 문서, 보고서 보관함': 'Archive for review results, originals, and reports',
  'Compliance 관련 일정 및 마감일': 'Compliance schedules and deadlines',
  '월간 일정 현황을 달력 형태로 확인': 'View monthly schedule status as a calendar',
  '중요 업데이트 및 알림': 'Important updates and notifications',
  'AI assistant': 'AI assistant',
  '안녕하세요. JB금융그룹 Compliance AI assistant입니다. 규정, 법령, 내부 정책에 대해 무엇이든 물어보세요.': 'Hello. I am the JB Financial Group Compliance AI assistant. Ask me about regulations, laws, or internal policies.',
  '추천 질문': 'Suggested Questions',
  '최근 금융소비자보호법 개정 내용은?': 'What changed recently in the Financial Consumer Protection Act?',
  '신규 대출 상품 출시 전 Compliance 체크리스트': 'Compliance checklist before launching a new loan product',
  'AML 정기 평가 필수 항목': 'Required items for regular AML assessment',
  '내부통제 시스템 운영 가이드라인': 'Internal control system operation guideline',
  '질문을 입력하세요...': 'Enter your question...',
  'Compliance 관련 질문을 입력하세요...': 'Enter a Compliance-related question...',
  '새 대화': 'New conversation',
  '새 채팅': 'New chat',
  '채팅 목록': 'Chat list',
  '과거 채팅 검색': 'Search past chats',
  '고정됨': 'Pinned',
  '최근 채팅': 'Recent chats',
  '핀 고정': 'Pin',
  '핀 고정 해제': 'Unpin',
  '문서 AI 검토': 'Document AI Review',
  '홈에서 업로드하고 바로 검토 요청': 'Upload from Home and request review immediately',
  '검토 요청': 'Request review',
  '검토 요청이 완료되었습니다.': 'Review request completed.',
  'AI 검토가 필요한 문장이 감지되었습니다.': 'A sentence requiring AI review was detected.',
  '규정 문구와 고지 내용을 한 번 더 확인하세요.': 'Please check the regulatory wording and notices again.',
  '검토할 문서를 끌어다 놓거나 파일을 선택해 업로드하세요.': 'Drag a document here or choose a file to upload.',
  '지원 형식: PDF, DOCX, TXT': 'Supported formats: PDF, DOCX, TXT',
  '파일 선택': 'Choose file',
  '최근 검토': 'Recent reviews',
  '검색 결과가 없습니다.': 'No search results.',
  '요청자': 'Requester',
  '일시': 'Date and time',
  '이슈': 'Issues',
  '원본': 'Original',
  '수정본': 'Revised',
  '보고서': 'Report',
  'AI 검토 결과': 'AI Review Result',
  '위험문장 하이라이트': 'Risk sentence highlights',
  '수정 제안 근거': 'Revision rationale',
  '완료': 'Completed',
  '검토 중': 'Reviewing',
  '확인 필요': 'Needs review',
  '제작하기': 'Create',
  '홈에서 업로드하고 바로 제작 요청': 'Upload from Home and request creation immediately',
  '제작 요청': 'Request creation',
  '교육 자료 제작 열기': 'Open training material creation',
  '전체 검토 보기': 'View all reviews',
  '전체 채팅 열기': 'Open full chat',
  '작업 이력': 'Work history',
  '요청하기': 'Request',
  '요청 내용': 'Request details',
  '교육 안내 문구': 'Training notice copy',
  '이미지 미리보기': 'Image preview',
  '결과 다운로드': 'Download result',
  '다가오는 일정': 'Upcoming schedule',
  '건 예정': 'scheduled items',
  '건 일정': 'scheduled items',
  '예정': 'scheduled',
  '예정된 일정 없음': 'No upcoming schedule',
  '일정 추가': 'Add schedule',
  '오늘': 'Today',
  '오늘의 일정': "Today's schedule",
  '일정이 없습니다.': 'No schedule.',
  '새 일정 추가': 'Add new schedule',
  '일정 수정': 'Edit schedule',
  '제목': 'Title',
  '카테고리': 'Category',
  '기간': 'Period',
  '시작 시간': 'Start time',
  '종료 시간': 'End time',
  '장소': 'Location',
  '관할 부서': 'Department',
  '메모': 'Memo',
  '세미나': 'Seminar',
  '감사': 'Audit',
  '워크샵': 'Workshop',
  '교육': 'Training',
  '회의': 'Meeting',
  '점검': 'Inspection',
  '기타': 'Other',
  '전체 알림 내역': 'All notifications',
  '모두 읽음 처리': 'Mark all as read',
  '안읽음': 'Unread',
  '모두 읽음': 'All read',
  '방금': 'Just now',
  '분 전': 'minutes ago',
  '5분 전': '5 minutes ago',
  '읽음': 'Read',
  '최근 알림': 'Recent notifications',
  '모든 알림 보기': 'View all notifications',
  '교육 자료 생성 완료': 'Training material created',
  '교육 포스터 생성 완료': 'Training poster created',
  'AI 검토 보고서 생성': 'AI review report created',
  '광고시안_Ver2_검토보고서.txt가 라이브러리에 저장되었습니다.': '광고시안_Ver2_검토보고서.txt has been saved to the library.',
  '금융소비자보호법_교육포스터.png가 라이브러리에 저장되었습니다.': '금융소비자보호법_교육포스터.png has been saved to the library.',
  '금융소비자보호법_교육자료.pptx가 라이브러리에 저장되었습니다.': '금융소비자보호법_교육자료.pptx has been saved to the library.',
  '신규 규정 업데이트': 'New regulation update',
  '계정과 시스템 설정을 관리하세요.': 'Manage account and system settings.',
  '이름': 'Name',
  '이메일': 'Email',
  '부서': 'Department',
  '직책': 'Role',
  '선임 Compliance 매니저': 'Senior Compliance Manager',
  '페이지를 찾을 수 없습니다': 'Page not found',
  '요청하신 주소가 존재하지 않습니다.': 'The requested address does not exist.',
  '홈으로 돌아가기': 'Back to Home',
  '김준또': 'Kim Juntto',
  '김준법': 'Kim Junbeop',
  '박정민': 'Park Jeongmin',
  '이서연': 'Lee Seoyeon',
  '건': 'items',
  '월': 'month',
  '년': 'year',
  '일': 'day',
  '오전': 'AM',
  '오후': 'PM',
};

const myanmarDictionary: Record<string, string> = {
  '준또배기': 'JunttoBaegi',
  'JB금융그룹': 'JB ဘဏ္ဍာရေးအုပ်စု',
  '법무팀': 'ဥပဒေရေးရာအဖွဲ့',
  '한국어': 'ကိုရီးယား',
  '영어': 'အင်္ဂလိပ်',
  '베트남어': 'ဗီယက်နမ်',
  '미얀마어': 'မြန်မာ',
  '캄보디아어': 'ခမာ',
  '홈': 'ပင်မ',
  'AI 채팅': 'AI စကားပြော',
  'AI 검토': 'AI စစ်ဆေးမှု',
  '교육 자료 제작': 'သင်တန်းပစ္စည်း ပြုလုပ်ခြင်း',
  '라이브러리': 'စာကြည့်တိုက်',
  '캘린더': 'ပြက္ခဒိန်',
  '설정': 'ဆက်တင်',
  '알림': 'အသိပေးချက်',
  '프로필': 'ပရိုဖိုင်',
  '언어 및 지역': 'ဘာသာစကားနှင့် ဒေသ',
  '언어': 'ဘာသာစကား',
  '시간대': 'အချိန်ဇုန်',
  '날짜 형식': 'ရက်စွဲပုံစံ',
  '로그아웃': 'ထွက်မည်',
  '모두 보기': 'အားလုံးကြည့်ရန်',
  '전체': 'အားလုံး',
  '저장': 'သိမ်းမည်',
  '취소': 'မလုပ်တော့',
  '다운로드': 'ဒေါင်းလုဒ်',
  '검색': 'ရှာဖွေရန်',
  '추가': 'ထည့်ရန်',
  '삭제': 'ဖျက်ရန်',
  '수정': 'ပြင်ရန်',
  '위젯 추가': 'ဝစ်ဂျက်ထည့်ရန်',
  '위젯 제거': 'ဝစ်ဂျက်ဖယ်ရှားရန်',
  '드래그해서 이동': 'ဆွဲ၍ရွှေ့ရန်',
  '홈에서 업로드하고 바로 검토 요청': 'ပင်မမှ အပ်လုဒ်တင်ပြီး စစ်ဆေးမှုတောင်းဆိုရန်',
  '홈에서 업로드하고 바로 제작 요청': 'ပင်မမှ အပ်လုဒ်တင်ပြီး ဖန်တီးမှုတောင်းဆိုရန်',
  '검토 요청': 'စစ်ဆေးမှုတောင်းဆိုရန်',
  '제작 요청': 'ဖန်တီးမှုတောင်းဆိုရန်',
  '전체 검토 보기': 'စစ်ဆေးမှုအားလုံးကြည့်ရန်',
  '전체 채팅 열기': 'ချက်အားလုံးဖွင့်ရန်',
  '교육 자료 제작 열기': 'သင်တန်းပစ္စည်းဖန်တီးမှု ဖွင့်ရန်',
  '최근 알림': 'လတ်တလော အသိပေးချက်',
  '모든 알림 보기': 'အသိပေးချက်အားလုံး',
  '모두 읽음 처리': 'အားလုံးဖတ်ပြီးအဖြစ် သတ်မှတ်ရန်',
  '안읽음': 'မဖတ်ရသေး',
  '모두 읽음': 'အားလုံးဖတ်ပြီး',
  '방금': 'ယခုပဲ',
  '분 전': 'မိနစ် အကြာ',
  '5분 전': '၅ မိနစ် အကြာ',
  '읽음': 'ဖတ်ပြီး',
  'AI assistant': 'AI assistant',
  'Compliance 전문 AI': 'Compliance အထူးပြု AI',
  '추천 질문': 'အကြံပြုမေးခွန်းများ',
  '질문을 입력하세요...': 'မေးခွန်းရေးပါ...',
  'Compliance 관련 질문을 입력하세요...': 'Compliance ဆိုင်ရာ မေးခွန်းရေးပါ...',
  '새 대화': 'စကားဝိုင်းအသစ်',
  '새 채팅': 'ချက်အသစ်',
  '채팅 목록': 'ချက်စာရင်း',
  '최근 채팅': 'လတ်တလော ချက်များ',
  '문서 AI 검토': 'စာရွက်စာတမ်း AI စစ်ဆေးမှု',
  '파일 선택': 'ဖိုင်ရွေးရန်',
  '최근 검토': 'လတ်တလော စစ်ဆေးမှု',
  '요청자': 'တောင်းဆိုသူ',
  '일시': 'နေ့ရက်/အချိန်',
  '이슈': 'ပြဿနာ',
  '원본': 'မူရင်း',
  '수정본': 'ပြင်ဆင်ထားသော',
  '보고서': 'အစီရင်ခံစာ',
  '완료': 'ပြီးဆုံး',
  '검토 중': 'စစ်ဆေးနေသည်',
  '확인 필요': 'စစ်ဆေးရန်လို',
  '제작하기': 'ပြုလုပ်ရန်',
  '작업 이력': 'လုပ်ဆောင်မှုမှတ်တမ်း',
  '요청하기': 'တောင်းဆိုရန်',
  '교육 안내 문구': 'သင်တန်းအသိပေးစာ',
  '이미지 미리보기': 'ပုံကြိုတင်ကြည့်ရှုမှု',
  '다가오는 일정': 'လာမည့်အစီအစဉ်',
  '건 예정': 'ခု လာမည်',
  '건 일정': 'ခု အစီအစဉ်',
  '예정': 'လာမည်',
  '일정 추가': 'အစီအစဉ်ထည့်ရန်',
  '오늘': 'ယနေ့',
  '오늘의 일정': 'ယနေ့အစီအစဉ်',
  '새 일정 추가': 'အစီအစဉ်အသစ်ထည့်ရန်',
  '일정 수정': 'အစီအစဉ်ပြင်ရန်',
  '제목': 'ခေါင်းစဉ်',
  '카테고리': 'အမျိုးအစား',
  '기간': 'ကာလ',
  '장소': 'နေရာ',
  '관할 부서': 'တာဝန်ခံဌာန',
  '메모': 'မှတ်စု',
  '교육': 'သင်တန်း',
  '회의': 'အစည်းအဝေး',
  '점검': 'စစ်ဆေးခြင်း',
  '기타': 'အခြား',
  '교육 자료 생성 완료': 'သင်တန်းပစ္စည်း ဖန်တီးပြီး',
  '교육 포스터 생성 완료': 'သင်တန်းပိုစတာ ဖန်တီးပြီး',
  'AI 검토 보고서 생성': 'AI စစ်ဆေးမှုအစီရင်ခံစာ ဖန်တီးပြီး',
  '계정과 시스템 설정을 관리하세요.': 'အကောင့်နှင့်စနစ် ဆက်တင်များကို စီမံပါ။',
  '이름': 'အမည်',
  '이메일': 'အီးမေးလ်',
  '부서': 'ဌာန',
  '직책': 'ရာထူး',
  '페이지를 찾을 수 없습니다': 'စာမျက်နှာ မတွေ့ပါ',
  '홈으로 돌아가기': 'ပင်မသို့ ပြန်သွားရန်',
};

const khmerDictionary: Record<string, string> = {
  '준또배기': 'JunttoBaegi',
  'JB금융그룹': 'ក្រុមហ៊ុនហិរញ្ញវត្ថុ JB',
  '법무팀': 'ក្រុមច្បាប់',
  '한국어': 'កូរ៉េ',
  '영어': 'អង់គ្លេស',
  '베트남어': 'វៀតណាម',
  '미얀마어': 'មីយ៉ាន់ម៉ា',
  '캄보디아어': 'ខ្មែរ',
  '홈': 'ទំព័រដើម',
  'AI 채팅': 'ជជែក AI',
  'AI 검토': 'ពិនិត្យ AI',
  '교육 자료 제작': 'បង្កើតសម្ភារៈបណ្តុះបណ្តាល',
  '라이브러리': 'បណ្ណាល័យ',
  '캘린더': 'ប្រតិទិន',
  '설정': 'ការកំណត់',
  '알림': 'ការជូនដំណឹង',
  '프로필': 'ប្រវត្តិរូប',
  '언어 및 지역': 'ភាសា និងតំបន់',
  '언어': 'ភាសា',
  '시간대': 'តំបន់ពេលវេលា',
  '날짜 형식': 'ទ្រង់ទ្រាយកាលបរិច្ឆេទ',
  '로그아웃': 'ចេញ',
  '모두 보기': 'មើលទាំងអស់',
  '전체': 'ទាំងអស់',
  '저장': 'រក្សាទុក',
  '취소': 'បោះបង់',
  '다운로드': 'ទាញយក',
  '검색': 'ស្វែងរក',
  '추가': 'បន្ថែម',
  '삭제': 'លុប',
  '수정': 'កែសម្រួល',
  '위젯 추가': 'បន្ថែមវីជិត',
  '위젯 제거': 'លុបវីជិត',
  '드래그해서 이동': 'អូសដើម្បីផ្លាស់ទី',
  '홈에서 업로드하고 바로 검토 요청': 'ផ្ទុកឡើងពីទំព័រដើម ហើយស្នើពិនិត្យភ្លាមៗ',
  '홈에서 업로드하고 바로 제작 요청': 'ផ្ទុកឡើងពីទំព័រដើម ហើយស្នើបង្កើតភ្លាមៗ',
  '검토 요청': 'ស្នើពិនិត្យ',
  '제작 요청': 'ស្នើបង្កើត',
  '전체 검토 보기': 'មើលការពិនិត្យទាំងអស់',
  '전체 채팅 열기': 'បើកជជែកពេញលេញ',
  '교육 자료 제작 열기': 'បើកបង្កើតសម្ភារៈបណ្តុះបណ្តាល',
  '최근 알림': 'ការជូនដំណឹងថ្មីៗ',
  '모든 알림 보기': 'មើលការជូនដំណឹងទាំងអស់',
  '모두 읽음 처리': 'សម្គាល់ថាបានអានទាំងអស់',
  '안읽음': 'មិនទាន់អាន',
  '모두 읽음': 'បានអានទាំងអស់',
  '방금': 'ទើបតែ',
  '분 전': 'នាទីមុន',
  '5분 전': '៥ នាទីមុន',
  '읽음': 'បានអាន',
  'AI assistant': 'AI assistant',
  'Compliance 전문 AI': 'AI ជំនាញ Compliance',
  '추천 질문': 'សំណួរណែនាំ',
  '질문을 입력하세요...': 'បញ្ចូលសំណួរ...',
  'Compliance 관련 질문을 입력하세요...': 'បញ្ចូលសំណួរពាក់ព័ន្ធ Compliance...',
  '새 대화': 'ការសន្ទនាថ្មី',
  '새 채팅': 'ជជែកថ្មី',
  '채팅 목록': 'បញ្ជីជជែក',
  '최근 채팅': 'ជជែកថ្មីៗ',
  '문서 AI 검토': 'ពិនិត្យឯកសារ AI',
  '파일 선택': 'ជ្រើសឯកសារ',
  '최근 검토': 'ពិនិត្យថ្មីៗ',
  '요청자': 'អ្នកស្នើ',
  '일시': 'កាលបរិច្ឆេទ/ពេល',
  '이슈': 'បញ្ហា',
  '원본': 'ដើម',
  '수정본': 'បានកែ',
  '보고서': 'របាយការណ៍',
  '완료': 'បានបញ្ចប់',
  '검토 중': 'កំពុងពិនិត្យ',
  '확인 필요': 'ត្រូវការពិនិត្យ',
  '제작하기': 'បង្កើត',
  '작업 이력': 'ប្រវត្តិការងារ',
  '요청하기': 'ស្នើ',
  '교육 안내 문구': 'អត្ថបទណែនាំបណ្តុះបណ្តាល',
  '이미지 미리보기': 'មើលរូបភាពជាមុន',
  '다가오는 일정': 'កាលវិភាគខាងមុខ',
  '건 예정': 'ធាតុខាងមុខ',
  '건 일정': 'ធាតុកាលវិភាគ',
  '예정': 'ខាងមុខ',
  '일정 추가': 'បន្ថែមកាលវិភាគ',
  '오늘': 'ថ្ងៃនេះ',
  '오늘의 일정': 'កាលវិភាគថ្ងៃនេះ',
  '새 일정 추가': 'បន្ថែមកាលវិភាគថ្មី',
  '일정 수정': 'កែកាលវិភាគ',
  '제목': 'ចំណងជើង',
  '카테고리': 'ប្រភេទ',
  '기간': 'រយៈពេល',
  '장소': 'ទីតាំង',
  '관할 부서': 'ផ្នែកទទួលខុសត្រូវ',
  '메모': 'កំណត់ចំណាំ',
  '교육': 'បណ្តុះបណ្តាល',
  '회의': 'ប្រជុំ',
  '점검': 'ត្រួតពិនិត្យ',
  '기타': 'ផ្សេងៗ',
  '교육 자료 생성 완료': 'បានបង្កើតសម្ភារៈបណ្តុះបណ្តាល',
  '교육 포스터 생성 완료': 'បានបង្កើតផ្ទាំងរូបភាពបណ្តុះបណ្តាល',
  'AI 검토 보고서 생성': 'បានបង្កើតរបាយការណ៍ពិនិត្យ AI',
  '계정과 시스템 설정을 관리하세요.': 'គ្រប់គ្រងគណនី និងការកំណត់ប្រព័ន្ធ។',
  '이름': 'ឈ្មោះ',
  '이메일': 'អ៊ីមែល',
  '부서': 'ផ្នែក',
  '직책': 'តួនាទី',
  '페이지를 찾을 수 없습니다': 'រកមិនឃើញទំព័រ',
  '홈으로 돌아가기': 'ត្រឡប់ទៅទំព័រដើម',
};

const languageDictionaries: Partial<Record<AppLanguage, Record<string, string>>> = {
  en: englishDictionary,
  vi: vietnameseDictionary,
  my: myanmarDictionary,
  km: khmerDictionary,
};

const textNodeOriginals = new WeakMap<Text, string>();
const attributeOriginals = new WeakMap<Element, Map<string, string>>();
const translatableAttributes = ['aria-label', 'title', 'placeholder'];

function translateText(text: string, dictionary: Record<string, string>) {
  return Object.entries(dictionary)
    .sort(([left], [right]) => right.length - left.length)
    .reduce((result, [source, target]) => result.split(source).join(target), text);
}

export function translateLabel(text: string, language: AppLanguage) {
  const dictionary = languageDictionaries[language];
  return dictionary ? translateText(text, dictionary) : text;
}

function shouldSkipElement(element: Element | null) {
  if (!element) return true;
  if (element.closest('[data-no-translate="true"]')) return true;
  return ['SCRIPT', 'STYLE', 'NOSCRIPT', 'TEXTAREA', 'INPUT', 'SELECT', 'OPTION'].includes(element.tagName);
}

function translateElementAttributes(element: Element, language: AppLanguage) {
  let originals = attributeOriginals.get(element);

  translatableAttributes.forEach((attribute) => {
    const value = element.getAttribute(attribute);
    if (!value) return;

    if (!originals) {
      originals = new Map<string, string>();
      attributeOriginals.set(element, originals);
    }

    if (!originals.has(attribute)) {
      originals.set(attribute, value);
    }

    const original = originals.get(attribute) ?? value;
    const nextValue = translateLabel(original, language);
    if (element.getAttribute(attribute) !== nextValue) {
      element.setAttribute(attribute, nextValue);
    }
  });
}

function translateNode(node: Node, language: AppLanguage) {
  if (node.nodeType === Node.TEXT_NODE) {
    const textNode = node as Text;
    if (shouldSkipElement(textNode.parentElement)) return;

    const current = textNode.nodeValue ?? '';
    if (!current.trim()) return;

    if (!textNodeOriginals.has(textNode)) {
      textNodeOriginals.set(textNode, current);
    }

    const original = textNodeOriginals.get(textNode) ?? current;
    const nextValue = translateLabel(original, language);
    if (textNode.nodeValue !== nextValue) {
      textNode.nodeValue = nextValue;
    }
    return;
  }

  if (node.nodeType !== Node.ELEMENT_NODE) return;

  const element = node as Element;
  if (shouldSkipElement(element)) return;

  translateElementAttributes(element, language);

  const walker = document.createTreeWalker(element, NodeFilter.SHOW_TEXT);
  let textNode = walker.nextNode();
  while (textNode) {
    translateNode(textNode, language);
    textNode = walker.nextNode();
  }

  element.querySelectorAll('*').forEach((child) => translateElementAttributes(child, language));
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState<AppLanguage>(() => {
    const defaultVersion = localStorage.getItem('jb_language_default_version');
    const saved = localStorage.getItem('jb_language');
    if (defaultVersion !== '2026-06-08-ko-default') return 'ko';
    return saved === 'ko' || saved === 'vi' || saved === 'en' || saved === 'my' || saved === 'km' ? saved : 'ko';
  });

  useEffect(() => {
    localStorage.setItem('jb_language', currentLanguage);
    localStorage.setItem('jb_language_default_version', '2026-06-08-ko-default');
    document.documentElement.lang = currentLanguage;
    translateNode(document.body, currentLanguage);

    const observer = new MutationObserver((mutations) => {
      mutations.forEach((mutation) => {
        mutation.addedNodes.forEach((node) => translateNode(node, currentLanguage));
      });
    });

    observer.observe(document.body, {
      childList: true,
      subtree: true,
    });

    return () => observer.disconnect();
  }, [currentLanguage]);

  const value = useMemo<LanguageContextValue>(() => {
    const current = languages.find((language) => language.code === currentLanguage) ?? languages[0];

    return {
      currentLanguage,
      currentLanguageLabel: current.label,
      languages,
      setLanguage: setCurrentLanguage,
    };
  }, [currentLanguage]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
